project:
  type: website
  output-dir: docs

website:
  title: "Local Minimum"
  description: "Research-in-progress blog on ML, physics, and biology"
  navbar:
    right:
      - about.qmd
      - license.qmd
      - icon: github
        href: https://github.com/drckf
  
  comments:
    giscus:
      repo: drckf/local-minimum
      repo-id: R_kgDOOVGEfA
      category: Announcements
      category-id: DIC_kwDOOVGEfM4Co189
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      theme: light

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    html-math-method: 
      method: mathjax
      options:
        tags: ams


